### ISSUE TITLE
Bleed Help

### ISSUE THREAD

**Issue by LACK0** [ten-A/Bleed#1]
Hi ten-A,
Found your Bleed.xcodeproj on Adobe forum:
https://community.adobe.com/t5/illustrator/setting-the-bleed-in-ai-via-javascript/td-p/8975095?page=2

Not sure how to use this. I would like to use this to add bleed lines to my files. I can do it manually but I wasn't sure if this method would allow me automate the process to add bleeds to many files by automating the process.

**Comment by ten-A** [comment]
Hi LACK0,
That thread discusses how to create a plugin to install it in Illustrator. Of course, I can create a plugin using the project in my repository, but knowledge of Illustrator SDK is essential for that.
